# Generated by Django 5.1.6 on 2025-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_fournisseur',
            field=models.BooleanField(default=False),
        ),
    ]
