# Generated by Django 5.1.6 on 2025-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatattachment',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
