# Generated by Django 5.1.6 on 2025-05-07 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': '2-Categorie',
            },
        ),
        migrations.CreateModel(
            name='SuperCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='image_super_Category')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('svg_icon', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '1-Super Categorie',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_id', models.IntegerField()),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(max_length=500)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image_Produit')),
                ('date', models.DateField(auto_now=True)),
                ('prix', models.FloatField()),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_likes', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.categorys')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='produits.produits')),
            ],
        ),
        migrations.CreateModel(
            name='RechercheUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=200)),
                ('date_recherche', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.categorys')),
            ],
            options={
                'verbose_name': '3-Sous Categorie',
            },
        ),
        migrations.AddField(
            model_name='produits',
            name='sous_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.souscategorys'),
        ),
        migrations.AddField(
            model_name='categorys',
            name='super_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.supercategorys'),
        ),
        migrations.CreateModel(
            name='ProduitAime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produits')),
            ],
            options={
                'verbose_name': 'Produit aimé',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
    ]
