# Generated by Django 5.1.6 on 2025-04-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur'),
        ),
        migrations.AddField(
            model_name='produits',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
