# Generated by Django 5.1.6 on 2025-02-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_souscategorys_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
