# Generated by Django 5.1.6 on 2025-04-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_commande_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='items',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.commande')),
            ],
        ),
    ]
