# Generated by Django 5.1.6 on 2025-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_produitaime'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitaime',
            name='nombre_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de likes'),
        ),
    ]
