# Generated by Django 5.1.6 on 2025-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_produitaime_nombre_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitaime',
            name='nombre_likes',
        ),
        migrations.AddField(
            model_name='produits',
            name='nombre_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de likes'),
        ),
    ]
