# Generated by Django 5.1.6 on 2025-04-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0004_commentaire_delete_critique'),
        ('produits', '0007_remove_produitaime_nombre_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournisseurs.fournisseur'),
        ),
    ]
