# Generated by Django 5.1.6 on 2025-04-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0005_fournisseur_user'),
        ('produits', '0008_alter_produits_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur'),
        ),
    ]
