# Generated by Django 5.1.6 on 2025-05-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_alter_produits_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='devise',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
