# Generated by Django 5.1.6 on 2025-05-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_produits_devise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='devise',
        ),
    ]
