# Generated by Django 5.1.6 on 2025-05-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_remove_produits_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='devise',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
