# Generated by Django 5.1.6 on 2025-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='fournisseurs/logos/'),
        ),
    ]
