# Generated by Django 5.1.6 on 2025-05-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0005_fournisseur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='descrition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
    ]
