# Generated by Django 5.1.6 on 2025-05-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0007_alter_fournisseur_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='descrition',
            new_name='description',
        ),
    ]
